import { zipSync } from "fflate";
import type { DownloadProjectFormat } from "types";

export interface ProjectImage {
  name: string;
  bytes: Uint8Array;
  nodeId: string;
}

const IMAGE_PLACEHOLDER_PATTERN = /__FIGMA_IMAGE_(.*?)__/g;

const GENERATED_PROJECT_ENGINES = {
  node: ">=24",
  pnpm: "^11",
} as const;

const GENERATED_PROJECT_VERSIONS = {
  next: "^16.2.12",
  react: "^19.2.8",
  reactDom: "^19.2.8",
  tailwindcss: "4.3.3",
  tailwindPostcss: "^4.3.3",
  tailwindVite: "^4.3.3",
  postcss: "^8.5.25",
  typesNode: "^26.1.2",
  typesReact: "^19.2.18",
  typesReactDom: "^19.2.4",
  typescript: "npm:@typescript/typescript6@^6.0.2",
  typescriptNative: "npm:typescript@^7.0.2",
  vite: "^8.2.0",
  viteReact: "^6.0.5",
} as const;

const removeExtension = (fileName: string) => fileName.replace(/\.[^.]+$/, "");
const toPackageName = (rootName: string) =>
  (rootName || "figma-export")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "") || "figma-export";
const toDartPackageName = (rootName: string) =>
  toPackageName(rootName).replace(/-/g, "_");

const encodeText = (text: string): Uint8Array => {
  if (typeof TextEncoder !== "undefined") {
    return new TextEncoder().encode(text);
  }

  const utf8 = unescape(encodeURIComponent(text));
  const bytes = new Uint8Array(utf8.length);
  for (let i = 0; i < utf8.length; i += 1) {
    bytes[i] = utf8.charCodeAt(i);
  }
  return bytes;
};

const writeJson = (value: unknown) =>
  encodeText(JSON.stringify(value, null, 2));

const isTailwindProject = (framework: string) => framework === "Tailwind";

const getImagePath = (
  image: ProjectImage,
  format: DownloadProjectFormat,
): string => {
  if (format === "flutter") {
    return `assets/images/${image.name}`;
  }
  if (format === "swiftui") {
    return removeExtension(image.name);
  }
  if (format === "html") {
    return `images/${image.name}`;
  }
  return `/images/${image.name}`;
};

export const extractProjectImageNodeIds = (code: string): Set<string> => {
  const nodeIds = new Set<string>();
  for (const match of code.matchAll(IMAGE_PLACEHOLDER_PATTERN)) {
    nodeIds.add(decodeURIComponent(match[1]));
  }
  return nodeIds;
};

export const replaceProjectImagePlaceholders = (
  code: string,
  images: ProjectImage[],
  format: DownloadProjectFormat,
): string => {
  const imagesByNodeId = new Map(images.map((image) => [image.nodeId, image]));
  const resolveImage = (encodedNodeId: string): ProjectImage => {
    const nodeId = decodeURIComponent(encodedNodeId);
    const image = imagesByNodeId.get(nodeId);
    if (!image) {
      throw new Error(`Missing exported image for Figma node ${nodeId}.`);
    }
    return image;
  };

  let replacedCode = code;
  if (format === "flutter") {
    replacedCode = replacedCode.replace(
      /NetworkImage\("__FIGMA_IMAGE_(.*?)__"\)/g,
      (_match, encodedNodeId: string) =>
        `AssetImage("${getImagePath(resolveImage(encodedNodeId), format)}")`,
    );
  }

  replacedCode = replacedCode.replace(
    IMAGE_PLACEHOLDER_PATTERN,
    (_match, encodedNodeId: string) =>
      getImagePath(resolveImage(encodedNodeId), format),
  );

  if (replacedCode.includes("__FIGMA_IMAGE_")) {
    throw new Error("Failed to resolve every exported image reference.");
  }

  return replacedCode;
};

export function generateProjectZip(
  code: string,
  framework: string,
  images: ProjectImage[],
  format: DownloadProjectFormat,
  rootName = "figma-export",
): Uint8Array {
  const files: Record<string, Uint8Array> = {};
  const usesTailwind = isTailwindProject(framework);
  const rootDir = rootName || "figma-export";
  const packageName = toPackageName(rootDir);

  if (format === "flutter") {
    files["pubspec.yaml"] = encodeText(`name: ${toDartPackageName(rootDir)}
description: Generated from Figma
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
`);

    files["lib/main.dart"] = encodeText(code);
    files["README.md"] = encodeText(`# ${rootDir}

Flutter source generated by Figma to Code.

## Requirements

- A current stable Flutter SDK
- A device, simulator, or supported desktop/web target

## Run the project

\`\`\`sh
flutter pub get
flutter run
\`\`\`

The generated UI starts in \`lib/main.dart\`. Exported images are stored in \`assets/images/\` and are already declared in \`pubspec.yaml\`.

## Before shipping

Review responsive behavior, semantics, navigation, state management, and platform-specific styling. This export is a clean visual starting point, not a complete production application.
`);
    files[".gitignore"] = encodeText(`.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
build/
`);
  } else if (format === "swiftui") {
    files[`${rootDir}/Assets.xcassets/Contents.json`] = writeJson({
      info: {
        author: "xcode",
        version: 1,
      },
    });
    files[`${rootDir}/README.md`] = encodeText(`# ${rootDir}

SwiftUI source generated by Figma to Code.

## Requirements

- A current stable Xcode release
- An iOS app target that uses SwiftUI

## Add it to Xcode

1. Create a new iOS app project using the SwiftUI interface.
2. Replace the generated \`ContentView.swift\` with this export's \`ContentView.swift\`.
3. Copy the image sets from \`Assets.xcassets\` into your app's asset catalog.
4. Build and run the app from Xcode.

## Before shipping

Review previews, accessibility labels, dynamic type, navigation, app state, and device-size behavior. The ZIP intentionally omits an \`.xcodeproj\` because Xcode project metadata is toolchain-specific and should be owned by your app.
`);
    files[`${rootDir}/ContentView.swift`] = encodeText(code);
  } else if (format === "html") {
    files[`${rootDir}/index.html`] = encodeText(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Figma Export</title>
    ${
      usesTailwind
        ? '<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4.3.3"></script>'
        : ""
    }
    <style>
      body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      }

      img { max-width: 100%; height: auto; }
    </style>
  </head>
  <body>
    ${code}
  </body>
</html>
`);
    files[`${rootDir}/README.md`] = encodeText(`# ${rootDir}

Static HTML generated by Figma to Code.

## Preview

Open \`index.html\` directly in a browser, or serve this directory with any static web server:

\`\`\`sh
python3 -m http.server 8080
\`\`\`

Then open <http://localhost:8080>.

Exported images are in \`images/\`.${
      usesTailwind
        ? " Tailwind CSS is loaded from a pinned browser CDN release, so an internet connection is required unless you replace it with a local build setup."
        : " This export has no runtime dependencies and works offline."
    }

## Before shipping

Review document semantics, keyboard behavior, responsive breakpoints, and image alternative text. The export reproduces the selected visual structure but cannot infer your product's behavior or content meaning.
`);
  } else if (format === "nextjs") {
    files["package.json"] = writeJson({
      name: packageName,
      private: true,
      version: "0.0.1",
      engines: GENERATED_PROJECT_ENGINES,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        next: GENERATED_PROJECT_VERSIONS.next,
        react: GENERATED_PROJECT_VERSIONS.react,
        "react-dom": GENERATED_PROJECT_VERSIONS.reactDom,
      },
      devDependencies: {
        "@types/node": GENERATED_PROJECT_VERSIONS.typesNode,
        "@types/react": GENERATED_PROJECT_VERSIONS.typesReact,
        "@types/react-dom": GENERATED_PROJECT_VERSIONS.typesReactDom,
        "@typescript/native": GENERATED_PROJECT_VERSIONS.typescriptNative,
        typescript: GENERATED_PROJECT_VERSIONS.typescript,
        ...(usesTailwind
          ? {
              "@tailwindcss/postcss":
                GENERATED_PROJECT_VERSIONS.tailwindPostcss,
              tailwindcss: GENERATED_PROJECT_VERSIONS.tailwindcss,
              postcss: GENERATED_PROJECT_VERSIONS.postcss,
            }
          : {}),
      },
    });

    files["next.config.ts"] =
      encodeText(`import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`);
    files["pnpm-workspace.yaml"] = encodeText(`allowBuilds:
  sharp: true
`);

    files["tsconfig.json"] = writeJson({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "ES6"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: [
        "next-env.d.ts",
        "**/*.ts",
        "**/*.tsx",
        ".next/types/**/*.ts",
        ".next/dev/types/**/*.ts",
      ],
      exclude: ["node_modules"],
    });

    files["app/globals.css"] = encodeText(
      usesTailwind
        ? `@import "tailwindcss";

img { max-width: 100%; height: auto; }
`
        : `body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

img { max-width: 100%; height: auto; }
`,
    );

    if (usesTailwind) {
      files["postcss.config.mjs"] = encodeText(
        `export default { plugins: ["@tailwindcss/postcss"] };
`,
      );
    }

    files["app/layout.tsx"] = encodeText(`import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Figma Export",
  description: "Generated from Figma",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`);

    const mainAttributes = usesTailwind
      ? ' className="container mx-auto p-4"'
      : "";
    files["app/page.tsx"] = encodeText(`export default function Page() {
  return (
    <main${mainAttributes}>
      ${code}
    </main>
  );
}
`);
    files["README.md"] = encodeText(
      `# ${rootDir}

Next.js project generated by Figma to Code.

## Requirements

- Node.js >=24
- pnpm ^11

## Run the project

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

Open <http://localhost:3000>. The generated UI is in \`app/page.tsx\`, global styles are in \`app/globals.css\`, and exported images are in \`public/images/\`.

The included \`pnpm-workspace.yaml\` permits only Next.js's \`sharp\` dependency to run its install script.

## Validate a production build

\`\`\`sh
pnpm typecheck
pnpm build
pnpm start
\`\`\`

## Before shipping

Review server/client component boundaries, metadata, responsive behavior, accessibility, data loading, and interactions. This export is intentionally dependency-light and does not invent application logic.
`,
    );
    files[".gitignore"] = encodeText(`node_modules/
.next/
out/
.env*
!.env.example
`);
  } else {
    files["package.json"] = writeJson({
      name: packageName,
      private: true,
      version: "0.0.1",
      type: "module",
      engines: GENERATED_PROJECT_ENGINES,
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        react: GENERATED_PROJECT_VERSIONS.react,
        "react-dom": GENERATED_PROJECT_VERSIONS.reactDom,
      },
      devDependencies: {
        "@types/react": GENERATED_PROJECT_VERSIONS.typesReact,
        "@types/react-dom": GENERATED_PROJECT_VERSIONS.typesReactDom,
        "@typescript/native": GENERATED_PROJECT_VERSIONS.typescriptNative,
        "@vitejs/plugin-react": GENERATED_PROJECT_VERSIONS.viteReact,
        typescript: GENERATED_PROJECT_VERSIONS.typescript,
        vite: GENERATED_PROJECT_VERSIONS.vite,
        ...(usesTailwind
          ? {
              "@tailwindcss/vite": GENERATED_PROJECT_VERSIONS.tailwindVite,
              tailwindcss: GENERATED_PROJECT_VERSIONS.tailwindcss,
            }
          : {}),
      },
    });

    files["index.html"] = encodeText(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Figma Export</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`);

    files["src/main.tsx"] = encodeText(`import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
${usesTailwind ? 'import "./index.css";' : ""}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`);

    const mainAttributes = usesTailwind
      ? ' className="container mx-auto p-4"'
      : "";
    files["src/App.tsx"] = encodeText(`export default function App() {
  return (
    <main${mainAttributes}>
      ${code}
    </main>
  );
}
`);

    files["vite.config.ts"] = encodeText(
      usesTailwind
        ? `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  plugins: [react(), tailwindcss()],
});
`
        : `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
    );

    files["tsconfig.json"] = writeJson({
      compilerOptions: {
        jsx: "react-jsx",
        moduleResolution: "bundler",
        target: "ES2020",
        module: "ESNext",
        strict: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        types: ["vite/client"],
      },
      include: ["src"],
    });

    if (usesTailwind) {
      files["src/index.css"] = encodeText(`@import "tailwindcss";

img { max-width: 100%; height: auto; }
`);
    }

    files["README.md"] = encodeText(
      `# ${rootDir}

Vite and React project generated by Figma to Code.

## Requirements

- Node.js >=24
- pnpm ^11

## Run the project

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

Open the URL printed by Vite. The generated UI is in \`src/App.tsx\`${
        usesTailwind ? ", Tailwind CSS is loaded from `src/index.css`," : ""
      } and exported images are in \`public/images/\`.

## Validate a production build

\`\`\`sh
pnpm typecheck
pnpm build
pnpm preview
\`\`\`

## Before shipping

Review component boundaries, responsive behavior, accessibility, state management, data loading, and interactions. This export is intentionally dependency-light and does not invent application logic.
`,
    );
    files[".gitignore"] = encodeText(`node_modules/
dist/
.env*
!.env.example
`);
  }

  for (const image of images) {
    if (format === "flutter") {
      files[`assets/images/${image.name}`] = image.bytes;
    } else if (format === "swiftui") {
      const assetName = removeExtension(image.name);
      files[`${rootDir}/Assets.xcassets/${assetName}.imageset/${image.name}`] =
        image.bytes;
      files[`${rootDir}/Assets.xcassets/${assetName}.imageset/Contents.json`] =
        writeJson({
          images: [
            {
              filename: image.name,
              idiom: "universal",
              scale: "1x",
            },
            {
              idiom: "universal",
              scale: "2x",
            },
            {
              idiom: "universal",
              scale: "3x",
            },
          ],
          info: {
            author: "xcode",
            version: 1,
          },
        });
    } else if (format === "html") {
      files[`${rootDir}/images/${image.name}`] = image.bytes;
    } else {
      files[`public/images/${image.name}`] = image.bytes;
    }
  }

  try {
    return zipSync(files, { level: 6 });
  } catch (error) {
    console.error("Zip creation failed:", error);
    throw new Error(
      "Failed to create project archive. The project might be too large or complex.",
    );
  }
}
